### ISSUE TITLE
Release 0.2.1

### ISSUE THREAD

**Issue by kellerkindt** [djc/corda-rpc#18]
Just stumbled upon the serde bug. It took me quite some time to figure out, that it is already fixed in the repo (f52fe386b1b632e35abc8b925169f9819be1ddc4) but not in the published version on [crates.io](https://crates.io/crates/oasis-amqp).

It would be neat if you could push the current state as 0.2.1 to crates.io

**Comment by djc** [comment]
Oh, happy to hear that this project is actually getting some use! I just published new versions of all the crates here. I decided to fix a future compiler incompatibility issue, which necessitated a semver-incompatible bump. Should be an easy fix -- just remove any `derive(Deserialize)` on struct definitions annotated with an `#[amqp_derive]` attribute.

Would like to hear a little more about what you're using this code for!

**Comment by kellerkindt** [comment]
I am evaluating whether its reasonable for me to build upon `oasis-amqp` for some basic message exchange with a qpid-proton broker. [Dove](https://crates.io/crates/dove) seems like an alternative, but it's rather (maybe too) minimalistic at the moment.

**Comment by djc** [comment]
Sounds good. Well, let me know if you need more changes.
